name: Android CI

on:
  push:
    branches: [ "ME-Alpha" ]
  pull_request:
    branches: [ "ME-Alpha" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

    - name: 'Decrypt github-packages properties'
      run: gcloud kms decrypt
          --ciphertext-file=encrypted-file_path
          --plaintext-file=file_path
          --location=europe-west1
          --keyring=ci-keyring
          --key=OUR_KEY

    - name: upload dev apk to cloud storage
      run: gsutil -q cp
          app/build/outputs/apk/dev/debug/app-dev-debug.apk
          destination
