name: Android CI

on:
  push:
    branches: [ "ME-Alpha" ]
  pull_request:
    branches: [ "ME-Alpha" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Assemble Gradle
      run: ./gradlew assembleRelease
      
    - name: Upload APK
      uses: actions/upload-artifact@v3.1.2
      with:
          name: Melange_ME.apk
          path: app/build/outputs/apk/release/*apk

    - name: move apk
      run: mv -fv app/build/outputs/apk/release/*.apk apk/Melange_ME.apk

    - name: Commit and Push APK
      run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add apk/Melange_ME.apk
          git commit -m "Add APK"
          git push
