name: Android CI

on:
  push:
    branches: [ "reizamuzayy-patch-1" ]
  pull_request:
    branches: [ "reizamuzayy-patch-1" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle
        #name: app-debug
        #path: app/build/outputs/apk/debug/app-debug.apk

    - name: Compile java code
      run: javac -Xlint:deprecation /src/main/java/io/github/usernameak/brewemulator/MainActivity.java
      working-directory: .
    - name: Instal Gradle
      run: sudo apt update; sudo apt install gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
