name: Build and Publish APK

on:
  push:
    branches:
      - main # Atur branch yang akan diawasi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8' # Sesuaikan dengan versi Java yang digunakan dalam proyek Anda

    - name: Build APK
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug # Atau tugas build yang sesuai

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk # Sesuaikan dengan path file APK yang dihasilkan
